# Generated by Django 4.2.9 on 2024-01-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('desciption', models.CharField(max_length=64, verbose_name='Описание')),
                ('premium', models.BooleanField(verbose_name='Премиум')),
                ('salary', models.IntegerField(max_length=64, verbose_name='Зарплата')),
                ('area_name', models.CharField(max_length=64, verbose_name='Территория')),
                ('published_at', models.DateTimeField(max_length=64, verbose_name='время публикации')),
            ],
        ),
    ]
