# Generated by Django 4.2.9 on 2024-01-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_vacancy_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='premium',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='area_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
