# Generated by Django 4.2.9 on 2024-01-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_vacancy_desciption_remove_vacancy_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
