# Generated by Django 4.2.9 on 2024-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_vacancy_salary_currency_alter_vacancy_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='wage_amount_by_years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('wage', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
