# Generated by Django 4.2.9 on 2024-01-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_wage_amount_by_years'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vacancy',
            new_name='new_vacancy',
        ),
    ]
