# Generated by Django 4.2.9 on 2024-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_rename_vacancy_new_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='wage_amount_by_years_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('wage', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
