# Generated by Django 4.2.9 on 2024-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_wage_amount_by_years_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='wage_amount_by_area_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64)),
                ('wage', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wage_amount_by_area_named',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=64)),
                ('wage', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
