# Generated by Django 4.2.9 on 2024-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_wage_amount_by_area_all_wage_amount_by_area_named'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage_amount_by_area_all',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wage_amount_by_years_all',
            name='amount',
            field=models.FloatField(),
        ),
    ]
